# Generated by Django 4.2.4 on 2023-08-22 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=100)),
                ("birthdate", models.DateField(default=datetime.date.today)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("national_id", models.CharField(max_length=30)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("province", models.CharField(default="", max_length=100)),
                ("district", models.CharField(default="", max_length=100)),
                ("sector", models.CharField(default="", max_length=100)),
                ("cellule", models.CharField(default="", max_length=100)),
                ("species", models.CharField(default="", max_length=100)),
                ("initial_qts", models.IntegerField(default=0)),
                ("villages", models.CharField(default="", max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
