# Generated by Django 4.2.4 on 2023-08-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdata",
            name="initial_qts",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
